//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurux.DLMS.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gurux.DLMS.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to activate the account?.
        /// </summary>
        internal static string AccountActivateWarning {
            get {
                return ResourceManager.GetString("AccountActivateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to close the account?.
        /// </summary>
        internal static string AccountCloseWarning {
            get {
                return ResourceManager.GetString("AccountCloseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset the account?.
        /// </summary>
        internal static string AccountResetWarning {
            get {
                return ResourceManager.GetString("AccountResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action accomplish..
        /// </summary>
        internal static string ActionImplemented {
            get {
                return ResourceManager.GetString("ActionImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to activate passive calendar?.
        /// </summary>
        internal static string ActivatePassiveCalendar {
            get {
                return ResourceManager.GetString("ActivatePassiveCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image activication FAILED..
        /// </summary>
        internal static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting activation to finish..
        /// </summary>
        internal static string ActivationInitiated {
            get {
                return ResourceManager.GetString("ActivationInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image activation succeeded..
        /// </summary>
        internal static string ActivationSuccessful {
            get {
                return ResourceManager.GetString("ActivationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to add selected items to the black list?.
        /// </summary>
        internal static string BlackListWarning {
            get {
                return ResourceManager.GetString("BlackListWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to capture the value?.
        /// </summary>
        internal static string CaptureWarning {
            get {
                return ResourceManager.GetString("CaptureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Files (*.csr)|*.csr|All files (*.*)|*.*.
        /// </summary>
        internal static string CertificateFilterTxt {
            get {
                return ResourceManager.GetString("CertificateFilterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected certificate(s)?.
        /// </summary>
        internal static string CertificateRemove {
            get {
                return ResourceManager.GetString("CertificateRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Registration Authority.
        ///#http://oid-info.com/get/2.16
        ///#Name;OID
        ///Algeria;2.16.dz(12)
        ///Andorra;2.16.ad(20)
        ///Argentina;2.16.ar(32)
        ///Australia;1.2.au(36)
        ///Austria;1.2.at(40)
        ///Bangladesh (the People&apos;s Republic of);2.16.bd(50)
        ///Benin;2.16.bj(204)
        ///Bolivia (Plurinational State of);2.16.bo(68)
        ///Brazil;2.16.br(76)
        ///Bulgaria;2.16.bg(100)
        ///Canada;2.16.ca(124)
        ///Cape Verde;2.16.cv(132)
        ///China (People&apos;s Republic of);1.2.cn(156)
        ///China (People&apos;s Republic of);2.16.cn(156)
        ///Côte d&apos;Ivoire;2.16.ci(384)
        ///Czech Republic;1.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-install M-Bus slave device..
        /// </summary>
        internal static string DeInstallMBusClient {
            get {
                return ResourceManager.GetString("DeInstallMBusClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset the selected object?.
        /// </summary>
        internal static string GeneralResetWarning {
            get {
                return ResourceManager.GetString("GeneralResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a hardware fault..
        /// </summary>
        internal static string HardwareFaultTxt {
            get {
                return ResourceManager.GetString("HardwareFaultTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image activated..
        /// </summary>
        internal static string ImageActivatedTxt {
            get {
                return ResourceManager.GetString("ImageActivatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image block size is.
        /// </summary>
        internal static string ImageBlockSize {
            get {
                return ResourceManager.GetString("ImageBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files (bin, xml)|*.bin;*.xml|Binary files (*.bin)|*.bin|XML files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string ImageFilesTxt {
            get {
                return ResourceManager.GetString("ImageFilesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image transfer is not enabled..
        /// </summary>
        internal static string ImageTransferDisabled {
            get {
                return ResourceManager.GetString("ImageTransferDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image transfered, but not activated..
        /// </summary>
        internal static string ImageTransferedNotActivatedTxt {
            get {
                return ResourceManager.GetString("ImageTransferedNotActivatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image transfer is enabled..
        /// </summary>
        internal static string ImageTransferEnabled {
            get {
                return ResourceManager.GetString("ImageTransferEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a inconsistent Class or Object..
        /// </summary>
        internal static string InconsistentClassTxt {
            get {
                return ResourceManager.GetString("InconsistentClassTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manufacturer settings are not present. Do you want to install them online from Gurux Web?.
        /// </summary>
        internal static string InstallManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("InstallManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install M-Bus slave device..
        /// </summary>
        internal static string InstallMBusClient {
            get {
                return ResourceManager.GetString("InstallMBusClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ASCII characters..
        /// </summary>
        internal static string InvalidASCII {
            get {
                return ResourceManager.GetString("InvalidASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Index..
        /// </summary>
        internal static string InvalidIndex {
            get {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OBIS code.
        /// </summary>
        internal static string InvalidObisCode {
            get {
                return ResourceManager.GetString("InvalidObisCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target..
        /// </summary>
        internal static string InvalidTarget {
            get {
                return ResourceManager.GetString("InvalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pem files (*.pem)|*.pem|Security files (*.cer)|*.cer|All files (*.*)|*.*.
        /// </summary>
        internal static string PemFilterTxt {
            get {
                return ResourceManager.GetString("PemFilterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected private key(s)?.
        /// </summary>
        internal static string PrivateKeyRemove {
            get {
                return ResourceManager.GetString("PrivateKeyRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to capture current values?.
        /// </summary>
        internal static string ProfileGenericCaptureWarning {
            get {
                return ResourceManager.GetString("ProfileGenericCaptureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select only one meter..
        /// </summary>
        internal static string ProfileGenericDeviceAmountWarning {
            get {
                return ResourceManager.GetString("ProfileGenericDeviceAmountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset historical data?.
        /// </summary>
        internal static string ProfileGenericResetWarning {
            get {
                return ResourceManager.GetString("ProfileGenericResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications updated..
        /// </summary>
        internal static string ProtocolsUpdatedTxt {
            get {
                return ResourceManager.GetString("ProtocolsUpdatedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports Read-Write denied..
        /// </summary>
        internal static string ReadWriteDeniedTxt {
            get {
                return ResourceManager.GetString("ReadWriteDeniedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset register value?.
        /// </summary>
        internal static string RegisterResetWarning {
            get {
                return ResourceManager.GetString("RegisterResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected device(s)?.
        /// </summary>
        internal static string RemoveDeviceConfirmation {
            get {
                return ResourceManager.GetString("RemoveDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected object?.
        /// </summary>
        internal static string RemoveObjectConfirmation {
            get {
                return ResourceManager.GetString("RemoveObjectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset alarm?.
        /// </summary>
        internal static string ResetAlarm {
            get {
                return ResourceManager.GetString("ResetAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must be restarted to apply the changes..
        /// </summary>
        internal static string RestartTxt {
            get {
                return ResourceManager.GetString("RestartTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string SaveChangesTxt {
            get {
                return ResourceManager.GetString("SaveChangesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to execute selected script?.
        /// </summary>
        internal static string ScriptTableExecute {
            get {
                return ResourceManager.GetString("ScriptTableExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to update password to the meter?.
        /// </summary>
        internal static string SecretSetWarning {
            get {
                return ResourceManager.GetString("SecretSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to set new password?.
        /// </summary>
        internal static string SetPasswordWarning {
            get {
                return ResourceManager.GetString("SetPasswordWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to synchronize the clock?.
        /// </summary>
        internal static string SynchronizeClock {
            get {
                return ResourceManager.GetString("SynchronizeClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a temporary failure..
        /// </summary>
        internal static string TemporaryFailureTxt {
            get {
                return ResourceManager.GetString("TemporaryFailureTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to set current time to the meter?.
        /// </summary>
        internal static string TimeSetWarning {
            get {
                return ResourceManager.GetString("TimeSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to set time zone of the PC to the meter?.
        /// </summary>
        internal static string TimeZoneSetWarning {
            get {
                return ResourceManager.GetString("TimeZoneSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unavailable object..
        /// </summary>
        internal static string UnavailableObjectTxt {
            get {
                return ResourceManager.GetString("UnavailableObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a undefined object..
        /// </summary>
        internal static string UndefinedObjectTxt {
            get {
                return ResourceManager.GetString("UndefinedObjectTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error..
        /// </summary>
        internal static string UnknownErrorTxt {
            get {
                return ResourceManager.GetString("UnknownErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Error : Device reports a unmatched type..
        /// </summary>
        internal static string UnmatchedTypeTxt {
            get {
                return ResourceManager.GetString("UnmatchedTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Manufacturer settings are available. Do you want to update them online from Gurux Web?.
        /// </summary>
        internal static string UpdateManufacturersOnline2Txt {
            get {
                return ResourceManager.GetString("UpdateManufacturersOnline2Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Manufacturer settings are available. Do you want to update them online from Gurux Web?.
        /// </summary>
        internal static string UpdateManufacturersOnlineTxt {
            get {
                return ResourceManager.GetString("UpdateManufacturersOnlineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value changed.
        /// </summary>
        internal static string ValueChangedTxt {
            get {
                return ResourceManager.GetString("ValueChangedTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image verification FAILED..
        /// </summary>
        internal static string VerificationFailed {
            get {
                return ResourceManager.GetString("VerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting verification to finish..
        /// </summary>
        internal static string VerificationInitiated {
            get {
                return ResourceManager.GetString("VerificationInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to add selected items to the white list?.
        /// </summary>
        internal static string WhiteListWarning {
            get {
                return ResourceManager.GetString("WhiteListWarning", resourceCulture);
            }
        }
    }
}
